### PR TITLE
Add list of supported eeproms to installation section of the docs

### PR DESCRIPTION
**Pull request by ABelliqueux**
Add list discussed here : https://github.com/JonathanDotCel/unirom8_bootdisc_and_firmware_for_ps1/issues/37

### CODE REVIEW

**Comment by JonathanDotCel** [comment]
Badass, thanks man :)

**Comment by danhans42** [comment]
If you need a scenario testing, and it would help I have a couple of 39sf040's.

**Comment by JonathanDotCel** [comment]
yeah mate, if you could stick one in a socket and see if uni will happily flash it, it'd be cool to get that one checked off, cheers :D

**Comment by danhans42** [comment]
No worries. I've got a socketed action replay, but not Xplorer
unfortunately.

I doubt it will work on the AR clone. Probably only will work on the first
256k?

I'll see what happens 🙂

**Comment by ABelliqueux** [comment]
I didn't think about that but yeah, you probably need a 512K mapper in order to be able to flash 512K roms...I'm interested to hear about the results!

Is the Xplorer the only cart with a 512K mapper ?

**Pull request merged**
